services:
  postgres:
    image: postgres:17
    container_name: promos-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: promos_user
      POSTGRES_PASSWORD: promos_password
      POSTGRES_DB: promos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
